######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 17 18:01:53 2014
######################################################################

TEMPLATE = app
TARGET = resident-seal 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h view.h
SOURCES += main.cpp mainwindow.cpp view.cpp

DESTDIR = ../bin/
MOC_DIR = ../build/
OBJECTS_DIR = ../build/
